(function (S, C, Y) {
    var yazilModule = angular.module("Cal.Yazil");
    yazilModule.run(function (textResource) {
    textResource.load("he-IL", {
        "Back": "חזור",
        "SystemLogin": "כניסה למערכת",
        "Login": "כניסה",
        "Welcome": "ברוכים הבאים",
        "Username": "שם משתמש",
        "Password": "סיסמה",
        "Logout": "יציאה",
        "LogoutMessage": "האם ברצונך להתנתק?",
        "Yes": "כן",
        "No":"לא",
        "ForgotPassword": "שכחתי שם משתמש / סיסמה",
        "AuthenticationFailed": "שם המשתמש או הסיסמה שגויים או שאינך רשום",
        "NextCredit": "זיכוי קרוב",
        "PreviousCredit": "זיכוי אחרון",
        "BalanceComment": '(סה"כ יתרות - כולל זיכוי קרוב)',
        "TotalBalance": 'סה"כ יתרות',
        "BalanceValueDate": "נכון לתאריך",
        "GoToAccountDetails": "לצפייה בפירוט חשבונות",
        "NoPreviousCredits": "זיכויים אחרונים",
        "PreviousCredits": "זיכויים אחרונים",
        "NextCredits": "זיכויים קרובים",
        "LegalTerms": "תנאים משפטיים",
        "InfoSecurity": "אבטחת מידע",
        "CustomerService": "שירות לקוחות",
        "MyAccountsTitle": "החשבונות שלי",
        "MyAccountTitle": "החשבון שלי",
        "MyAccounts": "פירוט חשבונות",
        "Home":"דף הבית",
        "MoreInfo": "עוד...",
        "CreditDate": "תאריך זיכוי",
        "CreditAmount": "סכום",
        "NoNetworkError": "אין חיבור רשת, לא ניתן לבצע כניסה",
        "AlertTitle": "הודעה",
        "AlertConfirm":"אישור",
        "AlertCancel": "ביטול",
        "AccountNumber": "חשבון מס'",
        "InvalidUsernameOrPassword": "יש להזין אותיות באנגלית או מספרים בלבד",
        "InvalidUsername": "יש להזין אותיות באנגלית או מספרים בלבד, בשדה שם משתמש",
        "InvalidPassword": "יש להזין אותיות באנגלית או מספרים בלבד, בשדה סיסמה",
        "NoAmount": "אין נתונים להצגה",
        "VersionUpdateRequired": "נדרש עדכון גרסה ע\"מ להשתמש באפליקציה",
        "ClickToUpdateVersion": "לחץ לעדכון גרסה",
        "MetadataError": "שגיאה בהפעלת האפליקציה",
        "Loading": "טוען",
        "Message": "הודעה",
        "ErrorMessage": "אירעה שגיאה בלתי צפויה",
        "NoNextCredits": "זיכויים קרובים",
        "MissingUserName": "נא להזין שם משתמש",
        "MissingPassword": "נא להזין סיסמה",
        "CommunicationError": "לא ניתן לקיים תקשורת. האם ברצונך לנסות שנית?",
        "Retry": "נסה שנית",
        "Close":"סגור"
    });
});

})(Simple, Cal, Cal.Yazil);
